version: ~> 1.0

services:
  - docker

import:
  - semantic-release/semantic-release:.travis/node.yml
  - semantic-release/semantic-release:.travis/node-versions.yml
  - semantic-release/semantic-release:.travis/semantic-release.yml
  - semantic-release/semantic-release:.travis/greenkeeper.yml
  - semantic-release/semantic-release:.travis/codecov.yml

addons:
  apt:
    packages:
      # See https://github.com/atom/ci
      - libsecret-1-dev

install:
  # See https://github.com/atom/ci
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh
  # Add apm to the PATH
  - export PATH=$PATH:~/atom/usr/bin
