name: Test
"on":
  push:
    branches:
      - master
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - '14.17'
          - 16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: UziTech/action-setup-atom@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      # waiting on https://github.com/ljharb/ls-engines/pull/23 to be fixed
      # - name: Ensure dependencies are compatible with the version of node
      #   run: npx ls-engines
      - run: npm run test:ci
  test:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npm ci
      - run: npm run lint
